---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: splunk
  namespace: prod
spec:
  releaseName: splunk-prod
  chart:
    git: git@github.com:asauerwein/helm-operator-get-started
    path: charts/mssp-helmchart
    ref: master
